#!/usr/bin/env ruby

require 'yaml'

# Read categories.yml
categories_file = '_data/categories.yml'
categories = YAML.load_file(categories_file)

# Ensure category directory exists
Dir.mkdir('category') unless Dir.exist?('category')

categories.each do |category|
  title = category['title']
  summary = category['summary']
  url = category['url']
  
  # Extract filename from URL (e.g., /category/ai/ -> ai)
  filename = File.basename(url.chomp('/'))
  
  # Generate regular category file
  filepath = "category/#{filename}.html"
  content = <<~TEMPLATE
    ---
    title: #{title}
    layout: default
    summary: #{summary}
    image: "/assets/blog.png"
    permalink: #{url}
    pagination:
      enabled: true
      per_page: 4
      category: "#{title}"
      permalink: /:num/
    ---
    {%- include post_index.html -%}

    <!-- This file has been auto-generated by generate_category_templates script -->

  TEMPLATE
  
  File.write(filepath, content)
  puts "Generated #{filepath}"
  
  # Generate popular category file
  popular_filepath = "category/#{filename}-popular.html"
  popular_url = url.chomp('/') + '/popular/'
  popular_summary = summary + '. Sorted by most popular'
  
  popular_content = <<~TEMPLATE
    ---
    title: #{title}
    layout: default
    summary: #{popular_summary}
    image: "/assets/blog.png"
    permalink: #{popular_url}
    pagination:
      enabled: true
      per_page: 4
      category: "#{title}"
      permalink: /:num/
      sort_field: 'clap_count'
    ---
    {%- include post_index.html -%}

    <!-- This file has been auto-generated by generate_category_templates script -->

  TEMPLATE
  
  File.write(popular_filepath, popular_content)
  puts "Generated #{popular_filepath}"
end

puts "Category template generation complete!"